export const FETCH_TAREFAS_SUCCESS = 'FETCH_TAREFAS_SUCCESS';
export const FETCH_UMA_TAREFA_SUCCESS = 'FETCH_UMA_TAREFA_SUCCESS';
export const FETCH_TAREFAS_FAILURE = 'FETCH_FAILURE';
export const FETCH_UMA_TAREFA_FAILURE = 'FETCH_UMA_TAREFA_FAILURE';
